### ISSUE TITLE
Repos - repository configurations

### ISSUE THREAD

**Issue by ghost** [o2r-project/o2r-shipper#19]
**Repository** ids are:
- `zenodo`
- `zenodo_sandbox`
- `b2share`
- `b2share_sandbox`
- `download`

**Tasks**

- [x] add master class for repo api wrappers; specific repos as inheritated classes
- [x] case zenodo
- [x] case eudat b2share
- [x] case download ERC
- [x] add api point `GET api/v1/recipient` with reponse

```{json}
{"recipient": [
    {"recipient": "zenodo",  "label": "Zenodo"},
    {"recipient": "zenodo_sandbox",  "label": "Zenodo Sandbox"},
    {"recipient": "b2share",  "label": "Eudat b2share"},
    {"recipient": "download",  "label": "Download"}
]}
```

**Comment by nuest** [comment]
(I can do these:)

- [x] update API docs with `../api/v1/recipient`
- [ ] add new endpoint to index response, see https://github.com/o2r-project/o2r-muncher/blob/ebbbf2401fa9da3c509bfbf8bfe1daffbdc702b5/index.js#L152

**Comment by ghost** [comment]
included with 07a10686e041a6cfb9ba9572961787bda24801ea
